package com.example.daniel.discovermovies_3.api;


import com.example.daniel.discovermovies_3.model.MoviesResponse;

import retrofit2.Call;
import retrofit2.http.GET;
import retrofit2.http.Path;
import retrofit2.http.Query;

/**
 * Created by Daniel on 4/27/17.
 */
public interface ApiInterface {
    @GET("movie/top_rated")
    Call<MoviesResponse> getTopRatedMovies(@Query("api_key") String apiKey);
    //This is the expected url to be generated by retrofit
    // http://api.themoviedb.org/3/movie/top_rated?api_key=12345678910111213

    @GET("movie/{id}")
    Call<MoviesResponse> getMovieDetails(@Path("id") int id, @Query("api_key") String apiKey);

    @GET("/search/movie")
    Call<MoviesResponse>getSearch(
            @Query("api_key") String apiKey,
            @Query("query") String movieName
    );
    //This is the expected url to be generated
    //https://api.themoviedb.org/3/search/movie?api_key=12345678910111213&query=summer
}